### ISSUE TITLE
Function names don't show up correctly.

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSysDiligence/mythril#377]
**Describe the bug**
The error report which Mythril prints doesn't always show the name of the function the issue is found in correctly.

**To Reproduce**
For instance, for the contract `Sale` in the source - 
https://etherscan.io/address/0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca#code

`mythril -xo json filename` produces the following report -
```
issues

address : 889
code : "ire(_multisigWallet != address(0)); ...""
description : "A possible integer overflow exists in the function `_function_0x58c23bf0`. The addition or multiplication may result in a value higher than the maximum representable integer."
filename : "../0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca.sol"
function : "_function_0x58c23bf0"
lineno : 377
title : "Integer Overflow "
type : "Warning"

address : 5993
code : "lse; bool public"
debug : "calldata_Sale_4 + calldata_...
description : "A possible integer overflow exists in the function `_function_0x58c23bf0`. The addition or multiplication may result in a value higher than the maximum representable integer."
filename : "../0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca.sol"
function : "_function_0x58c23bf0"
lineno : 359
title : "Integer Overflow "
type : "Warning"

address : 6007
code : "lse; bool public ..."
debug : "calldata_Sale_4 + calldata_..."
calldatasize_Sale: 0x4 callvalue: 0x0 "
description : "A possible integer overflow exists in the function `_function_0x58c23bf0`. The addition or multiplication may result in a value higher than the maximum representable integer."
filename : "../0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca.sol"
function : "_function_0x58c23bf0"
lineno : 359
title : "Integer Overflow "
type : "Warning"
success : true
```

**Expected behavior**
In each issue, the function name that's mentioned is `_function_0x58c23bf0`, as against what can be inferred from the line numbers of each of the issues -- `359` suggests it's a part of the contract definition, (so no real corresponding function name?) and `377` suggests it's from function `init()`

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version: Latest code pull from Github

**Comment by shashank-srikant** [comment]
Was skimming through other issues raised. Seems similar to #369.

**Comment by rocky** [comment]
An idea to consider is that we might be able to verify and match up based on a diff of the bytecode string

**Comment by norhh** [comment]
It seems the _function_<number> is being shown only for the data outside any function and inside the contract.

**Comment by shashank-srikant** [comment]
Thanks.

I reran the fixed master on the code i mentioned in my original post.
I now see that mythril's response is (edited/formatted for brevity) -
```

0
address : 889
contract : "unknown"
filename : "0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca.sol"
function : "init(string,uint256,uint256,uint256,uint256,address,address)"
lineno : 377
title : "Integer Overflow"
type : "Warning"

1
address : 5993
contract : "unknown"
filename : "0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca.sol"
function : "init(string,uint256,uint256,uint256,uint256,address,address)"
lineno : 359
title : "Integer Overflow"
type : "Warning"

2
address : 6007
contract : "unknown"
description : "A possible integer overflow exists in the function `init(string,uint256,uint256,uint256,uint256,address,address)`. The addition or multiplication may result in a value higher than the maximum representable integer."
filename : "0xf6da07a8ffb5683314715d8c7a1a5c952b4e74ca.sol"
function : "init(string,uint256,uint256,uint256,uint256,address,address)"
lineno : 359
title : "Integer Overflow"
type : "Warning"
``` 


Questions - 
- Why is `init` the function name associated with `issue 2`? The line number (`359`) suggests it is some operation to do with the variable `closed`?
Is this related to #424?
Mythril also dumps the `code` associated with each issue. This is the code pertaining to issue `2`. I couldn't really gather much from it - 

```
code : "lse; bool public saleInited = false; event TokenPurchase(address indexed purchaser, address indexed beneficiary, uint256 value, uint256 amount); function init( string _bonusPreset, uint256 _startTime, uint256 _endTime, uint256 _tokensLimit, uint256 _minimalPrice, DLCToken _token, address _multisigWallet ) public onlyConfigurer { require(!saleInited); require(_endTime >= _startTime); require(_tokensLimit > 0); require(_multisigWallet != address(0)); saleInited = true; token = _token; startTime = _startTime; endTime = _endTime; tokensLimit = _tokensLimit; multisigWallet = _multisigWallet; minimalPrice = _minimalPrice; bonusPreset = _bonusPreset; initBonuses(bonusPreset); } function activate() public onlyConfigurerOrOwner { require(!activated); require(!closed); activated = true; } function close() public onlyConfigurerOrOwner { activated = true; closed = true; } function setMultisigWallet(address _multisigWallet) public onlyConfigurerOrOwner { multisigWallet = _multisigWallet; } function () external payable { buyTokens(msg.sender); } function buyTokens(address beneficiary) public payable { require(beneficiary != address(0)); require(validPurchase()); uint256 amount = msg.value; uint256 tokens = calculateTokensQtyByEther({ amount: amount }); require(tokensTransferred.add(tokens) < tokensLimit); tokensTransferred = tokensTransferred.add(tokens); collected = collected.add(amount); token.purchase(beneficiary, tokens); emit TokenPurchase(msg.sender, beneficiary, amount, tokens); forwardFunds(); } function forwardFunds() internal { multisigWallet.transfer(msg.value); } function validPurchase() internal constant returns (bool) { bool withinPeriod = now >= startTime && now <= endTime; bool nonZeroPurchase = msg.value != 0; bool minimalPriceChecked = msg.value >= minimalPrice; return withinPeriod && nonZeroPurchase && minimalPriceChecked && activated && !closed; } function isStarted() public constant returns (bool) { return now > startTime; } function isEnded() public constant returns (bool) { return now > endTime; } } contract DoubleLandICO is Ownable { using SafeMath for uint256; DLCToken public token; Sale[] public sales; uint256 public softCap; uint256 public hardCap; uint public activatedSalesTotalCount = 0; uint public maxActivatedSalesTotalCount; address public multisigWallet; bool public isDeployed = false; function createSale(string _bonusPreset, uint256 _startTime, uint256 _endTime, uint256 _tokensL"
```

- Why are the contract names `unknown`? The command i ran was `myth -xo json file_name:Sale`. I provide the contract name while invoking Mythril. Shouldn't that come up in `contract`?

**Comment by shashank-srikant** [comment]
> Also the contract name is currently unknown because mythril is currently ignoring the contract names.

ok, so is this by design? will this be fixed?

**Comment by norhh** [comment]
Yes, that should be fixed for contracts from a file

**Comment by shashank-srikant** [comment]
@norhh Can we reopen this issue please.

I still see the gibberish function names, and am using the codebase version you recommended - 
https://github.com/ConsenSys/mythril/commit/657458bda31a868c54c8966a98b4b6a1ba841abd

On running `myth -xo json` on this code https://etherscan.io/address/0x3e84512f277A5081B9209831C51bCe665035D9DB#code
produces the following output  - 
```
1
address : 1304
code : "layer sends "
contract : "unknown"
debug : ""
description : "The return value of an external call is not checked. Note that execution continue even if the called contract throws."
filename : "0x3e84512f277A5081B9209831C51bCe665035D9DB.sol"
function : "fallback"
lineno : 46
title : "Unchecked CALL return value"
type : "Informational"

2
address : 1381
code : " amount = 100 ether; } "
contract : "unknown"
debug : ""
description : "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately. Consecutive calls: Call at address: 3202 Call at address: 2739 "
filename : "0x3e84512f277A5081B9209831C51bCe665035D9DB.sol"
function : "_function_0x7e7a2fbf"
lineno : 49
title : "Multiple Calls"
type : "Information"

3
address : 1414
contract : "unknown"
debug : ""
description : "The return value of an external call is not checked. Note that execution continue even if the called contract throws."
filename : "0x3e84512f277A5081B9209831C51bCe665035D9DB.sol"
function : "_function_0x7e7a2fbf"
lineno : 54
title : "Unchecked CALL return value"
type : "Informational"
```

The `fallback` message in error 1 seems related to that seen in #424.

**Comment by norhh** [comment]
can you try doing `solc --hashes <contract_name>` for this contract and check whats happening?

**Comment by shashank-srikant** [comment]
i've shifted to `master` from https://github.com/ConsenSys/mythril/commit/657458bda31a868c54c8966a98b4b6a1ba841abd
this is the output i now see on `solc --hashes`, and the function names show up correctly now on `myth -xo json`.

```
<<a bunch of warnings>>

======= 0x3e84512f277A5081B9209831C51bCe665035D9DB.sol:TheGame =======
Function signatures: 
e684aa5c: amountAlreadyPaidBack()
d954cbcb: amountInvested()
d4d5d32a: collectFee()
e811f50a: collectedFee()
7e7a2fbf: contribute_toTheGame()
51ec4525: first_player()
6b31ee01: jackpot()
18469491: lastPlayerPaid()
d10aee9c: mainPlayer()
9229c504: new_mainPlayer(address)
66ad484c: newfirst_player(address)
472016da: playersAddresses(uint256)
bed531fd: playersAmounts(uint256)
521d56c6: regeneration()
1ef3755d: restart()
146ca531: round()
1cc13dff: totalplayers()
```
things look right on this.

i then checked out again to https://github.com/ConsenSys/mythril/commit/657458bda31a868c54c8966a98b4b6a1ba841abd to see if i still see the previous error, and i don't. i now see the function names. very odd.

is there a cache or some such for modules i need to clear? would you know? i'm run these commands by spawning new terminal instances. that ought to be clearing things up.

**Comment by norhh** [comment]
Thats weird, As far as i know there is no cache except some signatures storage file which won't be of much relevance for file based input.
